import os
from building import *

cwd = GetCurrentDir()
group = []
src = Glob('*.c')
CPPPATH = [cwd, cwd + '/net_tester', cwd + '/../../board/ports/lcd', cwd + '/../../board/ports/ec11', cwd + '/../../board/ports/hzk']

list = os.listdir(cwd)
for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        group = group + SConscript(os.path.join(d, 'SConscript'))

group = group + DefineGroup('LVGL-port', src, depend = ['BSP_USING_LVGL'], CPPPATH = CPPPATH)

Return('group')
